-- Executes extracted production functions; assertions target observable room behavior.
publishLobbySettings()
local host=addHuman(10,1)
local guest=addHuman(20,2)
local otherHost=addHuman(30,3)
local otherGuest=addHuman(40,4)
local outsider=addHuman(50,5)
local traveler=addHuman(60,6)
updateHost()
for _,id in ipairs({"Room1","Room2","Room3","Room4"}) do
 expect(rooms[id].configured==false and rooms[id].expected==2,"new room must await host configuration")
 expect(workspace:GetAttribute("LobbyRoom_"..id.."_HostUserId")==0,"empty room inherited another room's host")
end
queueJoin(host,"Unknown",false,true)
queueJoin(host,false,false,true)
expect(not host.queued,"invalid UI room identifier was accepted")
queueJoin(host,"Room1",false,false)
expect(not host.queued,"physical join ignored proximity")
queueJoin(host,"Room1",false,true)
expect(host.queued and host.roomId=="Room1" and host.actor:GetAttribute("LobbyRoomId")=="Room1","explicit UI join did not enter its room")
expect(host.actor.Character.root.Anchored and host.actor.Character.pivot.roomId=="Room1","server did not place/anchor queued avatar")
expect(workspace:GetAttribute("LobbyRoom_Room1_HostUserId")==10,"first member did not become room host")
lobbyReady(host,true,rooms.Room1.revision)
expect(not host.ready and phase=="Lobby","unconfigured room accepted readiness")
local settings1={expectedPlayers=2,size="Small",aiCount=0,difficulty="Normal",population=100,startingResources="Rich",victory="Conquest",teamMode="FFA"}
configureLobby(host.actor,settings1)
expect(rooms.Room1.settings.size=="Small" and not rooms.Room1.configured,"host settings were not stored as unconfirmed configuration")
queueJoin(guest,"Room1",false,true)
expect(guest.queued and #queuedStates("Room1")==2,"guest could not join while its host was configuring")
local revision1=rooms.Room1.revision
configureLobbyComplete(guest.actor,revision1)
expect(not rooms.Room1.configured,"non-host committed room configuration")
for _,revision in ipairs({revision1-1,math.huge,0/0,"1"}) do
 configureLobbyComplete(host.actor,revision)
 expect(not rooms.Room1.configured,"stale or invalid revision committed room configuration")
end
configureLobbyComplete(host.actor,revision1)
expect(rooms.Room1.configured and workspace:GetAttribute("LobbyRoom_Room1_Configured")==true,"host could not atomically confirm current settings")
expect(workspace:GetAttribute("LobbyRoom_Room1_Status")=="Waiting","configured room did not publish waiting status")
lobbyReady(host,true,revision1)
expect(host.ready and not guest.ready and phase=="Lobby","room started before its other member was ready")
queueJoin(otherHost,"Room2",false,true)
local settings2=table.clone(settings1); settings2.size="Large"; settings2.difficulty="Hard"
configureLobby(otherHost.actor,settings2)
queueJoin(otherGuest,"Room2",false,true)
configureLobbyComplete(otherHost.actor,rooms.Room2.revision)
lobbyReady(otherHost,true,rooms.Room2.revision)
expect(rooms.Room2.configured and rooms.Room2.settings.size=="Large","second matching point was not equally configurable")
expect(host.ready and rooms.Room1.revision==revision1 and rooms.Room1.settings.size=="Small","configuring another room changed the first room")
expect(workspace:GetAttribute("LobbyRoom_Room2_HostUserId")==30 and workspace:GetAttribute("LobbyRoom_Room1_HostUserId")==10,"hosts were shared between rooms")
expect(workspace:GetAttribute("LobbyRoom_Room1_Players")==2 and workspace:GetAttribute("LobbyRoom_Room2_Players")==2,"room occupancy was combined")
lobbyReady(guest,true,revision1-1)
lobbyReady(guest,"true",revision1)
expect(not guest.ready,"stale revision or non-boolean readiness was accepted")
configureLobby(guest.actor,settings1)
expect(rooms.Room1.revision==revision1 and host.ready,"non-host changed room settings")
local injected=table.clone(settings1); injected.roomId="Room2"
configureLobby(host.actor,injected)
expect(rooms.Room1.revision==revision1 and rooms.Room1.configured and host.ready,"unsupported roomId payload changed configuration/readiness")
local invalid=table.clone(settings1); invalid.expectedPlayers=1
configureLobby(host.actor,invalid)
expect(rooms.Room1.expected==2 and rooms.Room1.revision==revision1,"room shrank below current occupancy")
queueJoin(host,"Room2",false,true)
expect(host.roomId=="Room1" and host.ready and rooms.Room1.revision==revision1,"full destination discarded original queue/readiness")
queueJoin(outsider,"Room1",false,true)
expect(not outsider.queued,"full room admitted additional player")
local revision2=rooms.Room2.revision
settings1.population=150
configureLobby(host.actor,settings1)
expect(rooms.Room1.settings.population==150 and not rooms.Room1.configured and not host.ready and not guest.ready,"settings edit retained configured/ready state")
expect(rooms.Room2.revision==revision2 and otherHost.ready and rooms.Room2.configured,"settings edit invalidated another room")
configureLobbyComplete(host.actor,revision1)
expect(not rooms.Room1.configured,"old confirmation committed edited settings")
lobbyReady(host,true,rooms.Room1.revision)
expect(not host.ready,"edited unconfirmed settings accepted readiness")
configureLobbyComplete(host.actor,rooms.Room1.revision)
lobbyReady(host,true,rooms.Room1.revision)
local guestOrder=guest.queueOrder
queueLeave(host)
expect(not host.queued and host.roomId==nil and not host.actor.Character.root.Anchored,"leave did not release avatar/room membership")
expect(workspace:GetAttribute("LobbyRoom_Room1_HostUserId")==20 and guest.queueOrder==guestOrder,"departed host did not migrate in queue order")
expect(rooms.Room1.configured and rooms.Room2.revision==revision2 and otherHost.ready,"host migration discarded remaining-room setup or changed another room")
host.queueCooldown=0
queueJoin(host,"Room1",false,true)
expect(workspace:GetAttribute("LobbyRoom_Room1_HostUserId")==20,"rejoining former host stole host authority")
lobbyReady(guest,true,rooms.Room1.revision)
expect(guest.ready and not host.ready,"current room revision could not be readied")
-- Empty rooms restore common defaults; a future host must configure again.
queueJoin(outsider,"Room3",false,true)
local abandoned=table.clone(settings1); abandoned.expectedPlayers=3; abandoned.population=200
configureLobby(outsider.actor,abandoned)
configureLobbyComplete(outsider.actor,rooms.Room3.revision)
expect(rooms.Room3.configured and rooms.Room3.expected==3,"third room did not accept host setup")
queueLeave(outsider)
expect(not rooms.Room3.configured and rooms.Room3.expected==2 and rooms.Room3.settings.population==100 and rooms.Room3.settings.size=="Medium","empty room retained departed host's settings")
expect(workspace:GetAttribute("LobbyRoom_Room3_HostUserId")==0,"empty room retained old host")
-- Every point can start a configured match; only its members enter the new battlefield.
queueJoin(traveler,"Room4",false,true)
local solo=table.clone(settings1); solo.expectedPlayers=1
configureLobby(traveler.actor,solo)
configureLobbyComplete(traveler.actor,rooms.Room4.revision)
expect(phase=="Lobby","confirming setup alone started before player readiness")
local keptRevision1=rooms.Room1.revision
local oldCharacter=traveler.actor.Character
lobbyReady(traveler,true,rooms.Room4.revision)
expect(phase=="Playing" and activeRoomId=="Room4" and generatedMaps==1,"configured fully ready room did not automatically start")
expect(traveler.playing and not traveler.inLobby and traveler.actor:GetAttribute("InLobby")==false,"selected player stayed in lobby state")
expect(traveler.actor.Character==nil and oldCharacter.destroyed,"start retained selected player's lobby avatar")
expect(host.queued and guest.queued and guest.ready and host.inLobby and guest.inLobby and rooms.Room1.revision==keptRevision1,"start consumed another room's membership/readiness")
expect(otherHost.queued and otherGuest.queued and otherHost.ready and rooms.Room2.configured and rooms.Room2.revision==revision2,"start consumed second waiting room setup")
expect(host.actor.Character and guest.actor.Character and not host.playing and not guest.playing,"waiting room lost avatars or acquired RTS factions")
expect(host.resetCalls==nil and guest.resetCalls==nil and otherHost.resetCalls==nil and otherGuest.resetCalls==nil,"actual battlefield cleanup reset waiting lobby actors")
expect(currentMatch.participants[60]==traveler and currentMatch.participants[10]==nil and currentMatch.participants[30]==nil,"battle roster crossed room boundaries")
expect(workspace:GetAttribute("ActiveBattleRoomId")=="Room4" and workspace:GetAttribute("MatchGeneration")==1,"fresh battlefield identity/generation missing")
local generation=matchGeneration
lobbyReady(otherGuest,true,rooms.Room2.revision)
startMatch(otherHost.actor)
expect(matchGeneration==generation and generatedMaps==1 and activeRoomId=="Room4" and otherGuest.ready,"second ready room replaced running battlefield")
outsider.queueCooldown=0
queueJoin(outsider,"Room4",false,true)
expect(not outsider.queued,"active room admitted new queued player")
queueLeave(host)
expect(not host.queued and guest.queued and guest.inLobby and traveler.playing,"waiting queue leave changed battle participants")
expect(not guest.ready and workspace:GetAttribute("LobbyRoom_Room1_HostUserId")==20,"waiting host/readiness failed during active battle")
local firstSeed=workspace:GetAttribute("MapSeed")
lobbyReset()
expect(activeRoomId=="Room2" and phase=="Playing" and generatedMaps==2,"fully ready waiting room could not progress after battlefield reset")
expect(otherHost.playing and otherGuest.playing and not otherHost.inLobby and not otherGuest.inLobby,"next match did not consume its own waiting room")
expect(traveler.inLobby and not traveler.playing and not rooms.Room4.configured and rooms.Room4.expected==2,"departing room did not return to fresh configuration")
expect(guest.inLobby and guest.queued and rooms.Room1.configured and not guest.ready,"battlefield reset changed a different waiting room's setup")
expect(workspace:GetAttribute("MapSeed")~=firstSeed and workspace:GetAttribute("MatchGeneration")==3,"next matching cycle reused previous battlefield generation")
print(string.format("PASS: %d actual configurable rooms / setup commit / readiness / host / battlefield checks",checks))
