local Rules=require("../src/ServerScriptService/ServerModules/MatchReportRules")
local checks=0
local function expect(condition,message)
 checks+=1
 assert(condition,message)
end
local function zeroResources(values)
 return values.food==0 and values.wood==0 and values.gold==0 and values.stone==0
end
local report=Rules.New("match_1",10)
expect(report~=nil,"valid match report missing")
expect(Rules.New("",10)==nil and Rules.New("bad id",10)==nil,"invalid match identity accepted")
expect(Rules.New("match",-1)==nil and Rules.New("match",math.huge)==nil and Rules.New("match",0/0)==nil,"invalid match start accepted")
local empty=Rules.Snapshot(report,10)
expect(empty.finished==false and empty.survivalSeconds==0 and empty.outcome=="pending","new report is not empty/pending")
expect(zeroResources(empty.resourcesDelivered) and zeroResources(empty.resourcesSpent),"starting balance incorrectly counted")
expect(Rules.Snapshot(report)==nil and Rules.Snapshot(report,9)==nil,"live survival requires a valid observation time")
expect(not Rules.Record({},1,"delivery",{resource="food",amount=10}),"foreign table accepted as a report")
expect(not Rules.Record(report,0,"delivery",{resource="food",amount=10}),"zero sequence accepted")
expect(not Rules.Record(report,1.5,"delivery",{resource="food",amount=10}),"fractional sequence accepted")
expect(not Rules.Record(report,math.huge,"delivery",{resource="food",amount=10}),"infinite sequence accepted")
expect(not Rules.Record(report,1,"clientBalance",{food=9999}),"client balance accepted as a fact")
for _,value in ipairs({-1,0,math.huge,0/0,"5",false}) do
 expect(not Rules.Record(report,1,"delivery",{resource="food",amount=value}),"invalid delivered amount accepted")
end
expect(not Rules.Record(report,1,"delivery",{resource="gems",amount=10}),"unknown resource accepted")
expect(not Rules.Record(report,1,"delivery",{resource="food",amount=10,client=true}),"unknown fact field accepted")
expect(Rules.Record(report,1,"delivery",{resource="food",amount=12.5}),"invalid facts consumed a sequence")
expect(not Rules.Record(report,1,"delivery",{resource="food",amount=12.5}),"duplicate delivery counted twice")
expect(Rules.Record(report,3,"delivery",{resource="wood",amount=15}),"later fact missing")
expect(not Rules.Record(report,2,"delivery",{resource="gold",amount=100}),"stale fact counted")
expect(Rules.Record(report,4,"delivery",{resource="gold",amount=7}) and Rules.Record(report,5,"delivery",{resource="stone",amount=8}),"four delivery resources missing")
local deliveries=Rules.Snapshot(report,12).resourcesDelivered
expect(deliveries.food==12.5 and deliveries.wood==15 and deliveries.gold==7 and deliveries.stone==8,"delivery totals wrong")
expect(not Rules.Record(report,6,"spend",{cost={wood=20,gold=-1}}),"mixed invalid cost accepted")
expect(not Rules.Record(report,6,"spend",{cost={wood=20,gems=1}}),"unknown cost key accepted")
expect(not Rules.Record(report,6,"spend",{cost={wood=20,gold=math.huge}}),"infinite cost accepted")
expect(not Rules.Record(report,6,"spend",{cost={wood=0}}),"no actual payment accepted")
expect(not Rules.Record(report,6,"spend",{cost={wood=10},refundable="yes"}),"nonboolean refund flag accepted")
expect(zeroResources(Rules.Snapshot(report,12).resourcesSpent),"invalid multipart cost partially counted")
expect(Rules.Record(report,6,"spend",{cost={food=50,wood=25,gold=10,stone=5},refundable=true}),"successful refundable payment rejected")
expect(not Rules.Record(report,6,"spend",{cost={food=50},refundable=true}),"duplicate payment counted twice")
expect(not Rules.Record(report,7,"refund",{spendId=2}),"refund without a payment accepted")
expect(Rules.Record(report,7,"refund",{spendId=6}),"actual full refund rejected")
expect(zeroResources(Rules.Snapshot(report,12).resourcesSpent),"refund did not remove net expense")
expect(not Rules.Record(report,8,"refund",{spendId=6}),"duplicate refund underflowed expense")
expect(Rules.Record(report,8,"spend",{cost={food=50},refundable=true}),"new queue payment rejected")
expect(not Rules.Record(report,9,"train",{subjectId="villager_1",role="unknown",spendId=8}),"unknown training role counted")
expect(Rules.Record(report,9,"train",{subjectId="villager_1",role="villager",spendId=8}),"successful spawned villager not counted")
expect(not Rules.Record(report,10,"refund",{spendId=8}),"completed unit payment remained refundable")
expect(not Rules.Record(report,10,"train",{subjectId="villager_1",role="military"}),"same model counted twice under another role")
expect(Rules.Record(report,10,"train",{subjectId=200,role="military"}),"successful military spawn missing")
expect(Rules.Record(report,11,"building",{subjectId="house_1"}),"completed building missing")
expect(not Rules.Record(report,12,"building",{subjectId="house_1"}),"completion re-notification counted twice")
expect(not Rules.Record(report,12,"building",{subjectId={}}),"unserializable subject ID accepted")
expect(not Rules.Record(report,12,"train",{subjectId="fake",role="villager",spendId=123}),"missing queue expense receipt accepted")
expect(Rules.Record(report,12,"damage",{beforeHP=15,afterHP=0}),"actual lethal damage missing")
expect(not Rules.Record(report,13,"damage",{beforeHP=0,afterHP=0}),"already dead target produced damage")
expect(not Rules.Record(report,13,"damage",{beforeHP=15,afterHP=-20}),"raw overkill counted as actual damage")
expect(not Rules.Record(report,13,"damage",{beforeHP=15,afterHP=20}),"repair counted as damage")
expect(not Rules.Record(report,13,"damage",{beforeHP=math.huge,afterHP=0}),"nonfinite HP accepted")
expect(Rules.Record(report,13,"damage",{beforeHP=100,afterHP=93.75}),"fractional actual damage lost")
expect(not Rules.Record(report,13,"damage",{beforeHP=100,afterHP=93.75}),"same damage repeated")
expect(Rules.Record(report,14,"kill",{subjectId="enemy_1",category="unit"}),"unit kill missing")
expect(not Rules.Record(report,15,"kill",{subjectId="enemy_1",category="building"}),"same victim counted again under changed category")
expect(Rules.Record(report,15,"kill",{subjectId="enemy_base",category="building"}),"building kill missing")
expect(Rules.Record(report,16,"loss",{subjectId="own_1",category="unit"}) and Rules.Record(report,17,"loss",{subjectId="own_house",category="building"}),"combat losses missing")
expect(not Rules.Record(report,18,"loss",{subjectId="own_1",category="unit"}),"same own casualty counted twice")
expect(not Rules.Record(report,18,"loss",{subjectId="unknown",category="resource"}),"resource exhaustion counted as casualty")
expect(not Rules.Finish(report,9,"win") and not Rules.Finish(report,math.huge,"win") and not Rules.Finish(report,30,"unknown"),"invalid finish accepted")
expect(Rules.Finish(report,40.5,"loss"),"real defeat did not finish the report")
expect(not Rules.Finish(report,50,"win"),"later match end overwrote an earlier defeat")
local final=Rules.Snapshot(report)
expect(final.finished and final.outcome=="loss" and final.outcomeLabel=="戰敗" and final.survivalSeconds==30.5,"defeat result or survival duration wrong")
expect(final.villagersTrained==1 and final.militaryTrained==1 and final.buildingsCompleted==1,"production totals wrong")
expect(final.damageDealt==21.25 and final.unitsKilled==1 and final.buildingsKilled==1 and final.unitsLost==1 and final.buildingsLost==1,"combat totals wrong")
expect(final.resourcesSpent.food==50 and final.resourcesSpent.wood==0,"net expense wrong after successful production")
expect(not Rules.Record(report,100,"delivery",{resource="food",amount=1000}) and not Rules.Record(report,101,"loss",{subjectId="cleanup",category="unit"}),"late facts or surrender cleanup changed finished stats")
expect(Rules.Snapshot(report,999).survivalSeconds==30.5,"spectating time changed frozen survival")
final.resourcesDelivered.food=9999; final.resourcesSpent.food=9999; final.labels.food="changed"
local copy=Rules.Snapshot(report)
expect(copy.resourcesDelivered.food==12.5 and copy.resourcesSpent.food==50 and copy.labels.food=="食物","replication copy aliases internal data")
local function safe(value)
 local kind=type(value)
 if kind=="number" then return value==value and value>=0 and value<=9007199254740991 end
 if kind=="string" or kind=="boolean" then return true end
 if kind~="table" then return false end
 for key,item in pairs(value) do if type(key)~="string" or key:sub(1,1)=="_" or not safe(item) then return false end end
 return true
end
expect(safe(copy) and copy.version==1,"snapshot exposes private/nonfinite/unserializable state")
local restarted=Rules.New("match_2",100)
local fresh=Rules.Snapshot(restarted,100)
expect(zeroResources(fresh.resourcesDelivered) and zeroResources(fresh.resourcesSpent) and fresh.damageDealt==0 and fresh.buildingsCompleted==0 and fresh.unitsLost==0,"new match inherited old counters")
expect(Rules.Record(restarted,1,"building",{subjectId="house_1"}),"new match inherited old sequence/model dedup")
expect(Rules.Finish(restarted,110,"win") and Rules.Snapshot(restarted).outcomeLabel=="勝利","win result missing")
local draw=Rules.New("match_3",0)
expect(Rules.Finish(draw,0,"draw") and Rules.Snapshot(draw).outcomeLabel=="無勝者","draw or zero-duration match missing")
local overflow=Rules.New("match_4",0)
expect(Rules.Record(overflow,1,"delivery",{resource="food",amount=9007199254740991}),"finite boundary amount rejected")
expect(not Rules.Record(overflow,2,"delivery",{resource="food",amount=1}),"counter overflow accepted")
expect(Rules.Record(overflow,2,"spend",{cost={wood=9007199254740991}}),"boundary expense missing")
expect(not Rules.Record(overflow,3,"spend",{cost={food=10,wood=1}}),"mixed expense overflow accepted")
expect(Rules.Snapshot(overflow,0).resourcesSpent.food==0,"overflowing expense partially counted")
local waiting=Rules.New("allied_waiting",100)
expect(Rules.Record(waiting,1,"delivery",{resource="wood",amount=45}),"ally predefeat delivery missing")
expect(not Rules.FreezeActivity(waiting,99) and not Rules.FreezeActivity(waiting,math.huge),"invalid elimination time froze activity")
expect(Rules.FreezeActivity(waiting,130),"natural elimination did not freeze activity")
expect(not Rules.FreezeActivity(waiting,140),"duplicate freeze changed survival duration")
local pending=Rules.Snapshot(waiting,999)
expect(not pending.finished and pending.outcome=="pending" and pending.outcomeLabel=="等待對局結果" and pending.survivalSeconds==30,"natural elimination prematurely lost or grew spectator survival")
expect(pending.resourcesDelivered.wood==45,"freezing erased real activity")
expect(not Rules.Record(waiting,2,"delivery",{resource="wood",amount=999}) and not Rules.Record(waiting,3,"loss",{subjectId="cleanup",category="unit"}),"spectator or cleanup changed frozen activity")
expect(not Rules.Finish(waiting,129,"win") and not Rules.Finish(waiting,150,"pending"),"invalid finalization of frozen report accepted")
expect(Rules.Finish(waiting,200,"win"),"eliminated ally could not receive final team win")
local alliedFinal=Rules.Snapshot(waiting)
expect(alliedFinal.finished and alliedFinal.outcome=="win" and alliedFinal.survivalSeconds==30 and alliedFinal.resourcesDelivered.wood==45,"team victory changed frozen activity or personal survival")
expect(not Rules.Finish(waiting,210,"loss") and not Rules.FreezeActivity(waiting,220),"finalized ally result changed later")
expect(safe(alliedFinal),"frozen report snapshot exposed internal lifecycle fields")
print(string.format("PASS: %d match report fact, dedup, refund, finish, snapshot, restart checks",checks))
