local Teams=require("../src/ServerScriptService/ServerModules/TeamRules")
local Reports=require("../src/ServerScriptService/ServerModules/MatchReportRules")
local Profiles=require("../src/ServerScriptService/ServerModules/ProfileRules")
local count=0
local function expect(ok,message) count+=1; assert(ok,message) end
local map=assert(Teams.assign("Teams",{{id=10,ai=false},{id=20,ai=false},{id=30,ai=false},{id=40,ai=false}}))
local config={DefaultCivilization="RiverHaven",Civilizations={RiverHaven={public=true}}}
local empty=Profiles.empty(config)
local ally=Reports.New("team_round",10)
expect(Reports.Record(ally,1,"damage",{beforeHP=100,afterHP=70}),"real activity before elimination missing")
expect(Reports.Record(ally,2,"delivery",{resource="food",amount=15}),"delivery before elimination missing")
expect(Reports.FreezeActivity(ally,25),"natural ally elimination failed to freeze")
expect(Teams.result(map,10,nil,false,false)=="pending","natural elimination immediately recorded a loss")
expect(not Profiles.result({outcome="pending",endedAt=1000}),"pending team outcome can enter persistent statistics")
expect(not Reports.Record(ally,3,"damage",{beforeHP=100,afterHP=0}),"eliminated ally accumulated later combat")
local winner,ended=Teams.winner(map,{30})
expect(ended and winner==map.teamById[10],"surviving teammate did not win the coalition")
local outcome=assert(Teams.result(map,10,winner,true,false))
expect(outcome=="win" and Reports.Finish(ally,100,outcome),"eliminated observer did not receive team victory")
local snapshot=Reports.Snapshot(ally,999)
expect(snapshot.finished and snapshot.outcome=="win" and snapshot.survivalSeconds==15 and snapshot.damageDealt==30 and snapshot.resourcesDelivered.food==15,"late team victory changed personal activity")
local result={results={team_round={outcome=outcome,endedAt=1000}}}
local saved=assert(Profiles.merge(empty,result,config))
expect(saved.pvpWins==1 and saved.pvpLosses==0,"completed team victory not merged as one win")
saved=assert(Profiles.merge(saved,result,config))
expect(saved.pvpWins==1 and saved.pvpLosses==0,"duplicate final event counted twice")
saved=assert(Profiles.merge(saved,{results={team_round={outcome="loss",endedAt=1100}}},config))
expect(saved.pvpWins==1 and saved.pvpLosses==0,"old result overwritten by later contradictory final event")
expect(not Reports.Finish(ally,110,"loss"),"final report settled twice")

local departed=Reports.New("departed_ally",10)
expect(Reports.FreezeActivity(departed,20),"departed ally did not initially freeze")
outcome=assert(Teams.result(map,10,nil,false,true))
expect(outcome=="loss" and Reports.Finish(departed,40,outcome),"already eliminated departure did not settle forfeit")
expect(Teams.result(map,10,winner,true,true)=="loss","allied victory turned departure into a win")
expect(not Reports.Finish(departed,100,"win"),"departed player's report was overwritten by allied victory")
snapshot=Reports.Snapshot(departed)
expect(snapshot.outcome=="loss" and snapshot.survivalSeconds==10,"departure inflated predeparture survival or changed outcome")
saved=assert(Profiles.merge(empty,{results={departed_ally={outcome=outcome,endedAt=1200}}},config))
saved=assert(Profiles.merge(saved,{results={departed_ally={outcome="win",endedAt=1300}}},config))
expect(saved.pvpWins==0 and saved.pvpLosses==1,"forfeit delta was overwritten or counted twice")

local draw=Reports.New("team_draw",0)
winner,ended=Teams.winner(map,{})
outcome=assert(Teams.result(map,10,winner,ended,false))
expect(outcome=="draw" and Reports.Finish(draw,10,outcome),"mutual elimination report missing draw")
expect(not Profiles.result({outcome=outcome,endedAt=1400}),"draw fabricated a persistent win or loss")
saved=assert(Profiles.merge(empty,{results={team_draw={outcome=outcome,endedAt=1400}}},config))
expect(saved.pvpWins==0 and saved.pvpLosses==0,"draw changed win/loss statistics")
expect(Teams.result(map,10,nil,true,true)=="loss","forfeit converted into a draw")

local coop=assert(Teams.assign("CoopAI",{{id=10,ai=false},{id=20,ai=false},{id=-10001,ai=true},{id=-10002,ai=true}}))
winner,ended=Teams.winner(coop,{10,20})
expect(ended and Teams.result(coop,10,winner,true,false)=="win" and Teams.result(coop,20,winner,true,false)=="win","cooperating humans did not share victory")
expect(not Profiles.eligible(true,2,2,true),"coop AI practice can farm persistent PvP wins")
expect(not Profiles.eligible(true,2,1,true),"mixed AI team practice can farm PvP wins")
expect(not Profiles.eligible(false,4,0,true),"Studio team game can write cloud statistics")
expect(not Profiles.eligible(true,4,0,false),"unstarted team game can write PvP results")
expect(Profiles.eligible(true,4,0,true),"completed human 2v2 excluded from eligible PvP")
local solo=assert(Teams.assign("FFA",{{id=10,ai=false}}))
winner,ended=Teams.winner(solo,{10})
expect(not ended and winner==nil and not Profiles.eligible(true,1,0,true),"single-player sandbox gained PvP results")
expect(not Teams.result(map,999,1,true,false),"spectator gained a team report outcome")
local departedState={id=10,forfeited=true}
local reconnectObserver={id=10,forfeited=false}
local registry={[10]=departedState}
expect(Teams.isParticipant(map,registry,departedState),"departed player's retained finalization state is not recognized")
expect(not Teams.isParticipant(map,registry,reconnectObserver),"reconnect observer gained the departed participant's result authority")
print(string.format("PASS: %d actual team / frozen report / profile merge lifecycle checks",count))
