local Rules=require("../src/ReplicatedStorage/Shared/TouchRules")
local checks=0
local function expect(ok,message) checks+=1; assert(ok,message) end
local state=Rules.new()
Rules.begin(state,"tap",100,100,0,false)
local released=Rules.finish(state,"tap",105,104,0.2,false)
expect(released.tap and released.place,"ordinary tap should select or place")
Rules.begin(state,"drag",100,100,1,false)
Rules.move(state,"drag",150,100,false)
released=Rules.finish(state,"drag",100,100,1.3,false)
expect(not released.tap and released.place,"returned drag must not select but may place a building")
Rules.begin(state,"held",100,100,2,false)
released=Rules.finish(state,"held",100,100,3,false)
expect(not released.tap and released.place,"long press must not accidentally select")
Rules.begin(state,"blocked",100,100,4,true)
released=Rules.finish(state,"blocked",200,200,4.2,false)
expect(not released.tap and not released.place,"UI-origin touch leaked onto world")
Rules.begin(state,"cross",100,100,5,false)
Rules.move(state,"cross",200,200,true)
released=Rules.finish(state,"cross",100,100,5.2,false)
expect(not released.tap and not released.place,"UI crossing must stay blocked after leaving UI")
Rules.begin(state,"a",100,100,6,false)
Rules.begin(state,"b",200,100,6.1,false)
local pair=Rules.pair(state)
expect(pair and pair.x==150 and pair.y==100 and pair.distance==100,"two fingers do not produce a camera gesture")
released=Rules.finish(state,"a",100,100,6.2,false)
expect(not released.tap and not released.place,"first lifted pinch finger issued a command")
expect(not Rules.single(state),"remaining pinch finger became a placement drag")
released=Rules.finish(state,"b",200,100,6.3,false)
expect(not released.tap and not released.place,"second lifted pinch finger issued a command")
Rules.begin(state,"world",100,100,7,false)
Rules.begin(state,"UI",200,100,7.1,true)
expect(not Rules.pair(state),"world plus UI touch moved the camera")
released=Rules.finish(state,"UI",200,100,7.2,true)
released=Rules.finish(state,"world",100,100,7.3,false)
expect(not released.tap and not released.place,"partially blocked two-finger gesture issued a command")
Rules.begin(state,"a",100,100,8,false)
Rules.begin(state,"b",200,100,8.1,false)
Rules.begin(state,"c",300,100,8.2,false)
expect(not Rules.pair(state),"three fingers used unstable camera pairing")
Rules.reset(state)
expect(not Rules.finish(state,"a",100,100,8.3,false),"modal/focus reset let old touch finish")
expect(not Rules.begin(state,"bad",0/0,0,9,false),"NaN pointer accepted")
expect(not Rules.begin(state,"bad",math.huge,0,9,false),"infinite pointer accepted")
Rules.begin(state,"a",100,100,9,false)
Rules.move(state,"a",math.huge,100,false)
released=Rules.finish(state,"a",100,100,9.2,false)
expect(not released.tap and not released.place,"invalid movement recovered command permission")
Rules.begin(state,"a",100,100,10,false)
expect(not Rules.begin(state,"a",110,100,10.1,false) and #state.order==1,"duplicate touch created a phantom second finger")
released=Rules.finish(state,"a",100,100,9,false)
expect(not released.tap and not released.place,"backwards event time accepted")
expect(Rules.zoom(160,100,200)==80,"spreading fingers should zoom in")
expect(Rules.zoom(160,100,50)==320,"pinching fingers should zoom out")
expect(Rules.zoom(160,100,1000)==65 and Rules.zoom(160,100,10)==360,"zoom escaped camera limits")
expect(Rules.zoom(160,0,100)==160 and Rules.zoom(160,100,0)==160,"near-zero pinch distance changed zoom")
expect(Rules.zoom(160,0/0,100)==160,"NaN pinch changed zoom")
expect(Rules.validMode("select") and Rules.validMode("move") and Rules.validMode("gather") and Rules.validMode("attack") and Rules.validMode("build"),"known command modes unavailable")
expect(not Rules.validMode("buy") and not Rules.validMode(nil),"unknown command mode allowed")
expect(Rules.inRect(10,20,10,20,100,44),"UI top-left boundary should block")
expect(not Rules.inRect(110,20,10,20,100,44) and not Rules.inRect(10,64,10,20,100,44),"ground immediately beside/below UI should remain clickable")
expect(not Rules.inRect(10,19.9,10,20,100,44),"ground immediately above UI was blocked")
expect(not Rules.inRect(0/0,20,10,20,100,44) and not Rules.inRect(10,20,10,20,-100,44),"invalid UI geometry blocked world input")
Rules.begin(state,"held",100,100,11,false)
Rules.cancelCommands(state)
expect(#state.order==1 and not Rules.single(state),"mode action forgot a held finger")
Rules.begin(state,"next",200,100,11.1,false)
expect(Rules.pair(state)~=nil,"command cancellation should retain camera gesture IDs")
released=Rules.finish(state,"next",200,100,11.2,false)
expect(not released.tap and not released.place,"new finger after mode action became a false solo command")
released=Rules.finish(state,"held",100,100,11.3,false)
expect(not released.tap and not released.place,"held finger after mode action recovered command permission")
local Focus=require("../src/ReplicatedStorage/Shared/CameraFocus")
local attributes,commits={},{}
local lastApplied,cameraDestination,appliedCount=0,nil,0
local destination={X=0,Y=0,Z=0}
local player={GetAttribute=function(_,key) return attributes[key] end}
function player:SetAttribute(key,value)
 local changed=attributes[key]~=value
 attributes[key]=value
 if key=="CameraFocusRevision" and changed then
  table.insert(commits,{revision=value,position=attributes.CameraFocus})
  if Focus.IsNew(value,lastApplied) then lastApplied=value; cameraDestination=attributes.CameraFocus; appliedCount+=1 end
 end
end
expect(Focus.Request(player,destination),"initial focus request failed")
cameraDestination={X=100,Y=0,Z=100} -- A local pan does not change the requested destination attribute.
expect(Focus.Request(player,destination),"repeated destination request failed")
expect(#commits==2 and appliedCount==2 and cameraDestination==destination,"same home position did not recenter after a pan")
expect(commits[1].position==destination and commits[2].position==destination and commits[1].revision==1 and commits[2].revision==2,"revision published before position or failed to increase")
expect(not Focus.IsNew(1,lastApplied) and not Focus.IsNew(2,lastApplied),"stale or duplicate focus revision reapplied")
expect(Focus.IsNew(attributes.CameraFocusRevision,0),"request made before listener binding could not be replayed at initialization")
local before=attributes.CameraFocusRevision
expect(not Focus.Request(player,nil) and attributes.CameraFocusRevision==before,"missing destination consumed a focus revision")
for _,bad in ipairs({-1,0.5,math.huge,0/0,"2",false}) do
 attributes.CameraFocusRevision=bad
 expect(not Focus.Request(player,{X=200,Y=0,Z=200}) and attributes.CameraFocus==destination,"invalid revision reset sequence or partially committed a position")
 expect(not Focus.IsNew(bad,0),"invalid focus revision accepted by listener")
end
attributes.CameraFocusRevision=9007199254740991
expect(not Focus.Request(player,destination),"exhausted exact-integer revision wrapped into an old request")
attributes.CameraFocusRevision=20
expect(Focus.Request(player,destination) and attributes.CameraFocusRevision==21,"existing client request sequence was reset")
local function edge(rawX,rawY,insetX,insetY,width,height,expectedX,expectedY,message)
 local x,y=Rules.edgeDirection(rawX,rawY,insetX,insetY,width,height)
 expect(x==expectedX and y==expectedY,message)
end
-- Desktop 1280x720 window, 58px core top inset: the safe height is 662,
-- so a physical cursor at y=719 must reach the bottom edge after conversion.
edge(640,719,0,58,1280,662,0,1,"bottom edge ignored the last visible pixel below the top inset")
edge(640,59,0,58,1280,662,0,-1,"top safe-area edge did not scroll up")
edge(1,400,0,58,1280,662,-1,0,"left safe-area edge did not scroll left")
edge(1279,400,0,58,1280,662,1,0,"right safe-area edge did not scroll right")
edge(640,400,0,58,1280,662,0,0,"center cursor scrolled camera")
edge(640,57,0,58,1280,662,0,0,"cursor over core top bar scrolled camera")
edge(1280,400,0,58,1280,662,0,0,"cursor outside right safe boundary scrolled camera")
edge(640,720,0,58,1280,662,0,0,"cursor outside bottom safe boundary scrolled camera")
edge(850,391,59,58,792,334,1,1,"device and core insets did not preserve corner scrolling")
edge(0/0,719,0,58,1280,662,0,0,"non-finite pointer scrolled camera")
edge(640,719,0,58,-1280,662,0,0,"invalid safe-area dimensions scrolled camera")
edge(nil,719,0,58,1280,662,0,0,"missing pointer coordinate scrolled camera")
print(string.format("PASS: %d touch / camera focus sequence / safe-area input checks",checks))
